apiVersion: v1
kind: Service
metadata:
  name: iris-api-service
  namespace: iris-classifier
spec:
  type: LoadBalancer
  selector:
    app: iris-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200

